### ISSUE TITLE
Command "ls" showing the wrong directory on windows

### ISSUE THREAD

**Issue by efraimgentil** [aeshell/cloverxell#87]
When start the cloverxell, and try to use the "ls" command is showing the wrong direcotry

![testecloverxell](https://cloud.githubusercontent.com/assets/2091945/5455660/9d44cac8-8524-11e4-8642-a573b4ea8c1d.png)

**Comment by eprogramming** [comment]
https://issues.jboss.org/browse/AESH-298

**Comment by eprogramming** [comment]
thanks @efraimgentil and https://github.com/jerr/ !
