### ISSUE TITLE
Aesh not found

### ISSUE THREAD

**Issue by felipewmartins** [aeshell/cloverxell#99]
After delete my .m2 directory, i performed the mvn clean package, but the aesh dependency is not found on repository.

![print](https://cloud.githubusercontent.com/assets/5208478/5714350/2c2c5382-9aa6-11e4-9e0e-019f5d2cc33c.png)

**Comment by eprogramming** [comment]
yes. we move to snapshot version
you can clone aesh and aesh-extensions then do clean install.

**Comment by danielsoro** [comment]
Clone aesh and aesh-extensions and use grade to build and install.
./gradlew install :)

On Tuesday, January 13, 2015, Helio Frota <notifications@github.com> wrote:

> yes. we move to snapshot version
> you can clone aesh and aesh-extensions then do clean install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aeshell/cloverxell/issues/99#issuecomment-69680611>.
>


-- 
Daniel Cunha (soro)

**Comment by eprogramming** [comment]
readme updated , thanks !
https://github.com/aeshell/cloverxell/blob/master/README.md
